def make_state() -> dict:
    return {
        "engine_parameters" : {
            "oxidizer" : None,
            "fuel" : None,
            "Pc" : None,
            "MR" : None,
            "throat_sizing_method" : None,
            "mass_flow_rate" : None,
            "Rt" : None,
            "N_injectors" : None,
            "injector_velocity_ratio" : None,
            "CEA_Obj_SI_units" : None,
            "CEA_Obj_default_units" : None,
            "Tc" : None,
            "Isp" : None,
            "Ivac" : None,
            "C_star" : None,
            "chamber_Cp" : None,
            "chamber_Pr" : None,
            "chamber_viscosity" : None,
            "species_mass_fractions" : None,
            "station_T_gas" : None,
            "station_T_aw" : None,
            "station_gamma" : None,
            "station_mach" : None,
        },
        "nozzle_parameters" : {
            "CR" : None,
            "eps" : None,
            "L_star" : None,
            "nozzle_type" : None,
            "nozzle_length_percentage" : None,
            "nozzle_angle" : None,
            "nozzle_resolution" : None,
            "At" : None,
            "x" : None,
            "R_x" : None,
            "eps_x" : None,
            "zone_x" : None,
            "station_x" : None,
            "station_R" : None,
            "station_eps" : None,
            "station_zone" : None,
        },
        "coolant_parameters" : {
            "coolant" : None,
            "coolant_mass_flow_rate" : None,
            "coolant_inlet_temperature" : None,
            "coolant_inlet_pressure" : None,
            "station_coolant_T" : None,
            "station_coolant_p" : None,
            "station_coolant_H" : None,
            "station_coolant_k" : None,
            "station_coolant_rho" : None,
            "station_coolant_velocity" : None,
            "station_coolant_Re" : None,
            "station_coolant_Pr" : None,
        },
        "channel_parameters" : {
            "wall_material" : None,
            "wall_thickness" : None,
            "N_cooling_channels" : None,
            "interpolation_type" : None,
            "jacket_resolution" : None,
            "channel_roughness" : None,
            "control_points_position" : None,
            "control_points_cw" : None,
            "control_points_ch" : None,
            "station_cw" : None,
            "station_ch" : None,
            "station_landwidth" : None,
            "station_Dh" : None,
            "station_A_channel" : None,
            "station_A_heat_transfer" : None,
        },
        "solver_options" : {
            "pressure_drop_model" : None,
            "cold_side_model" : None,
            "hot_side_model" : None,
            "wall_model" : None,
        },
        "results" : {
            "Q_flux" : None,
            "T_cold_wall" : None,
            "T_hot_wall" : None,
            "h_coolant" : None,
            "h_gas" : None,
            "T_field" : None,
            "mesh" : None,
        },
}